In [1]:
import cdsapi
import climetlab as cml
import numpy as np
import matplotlib.pyplot as plt
import geopandas
import geopy
import xarray as xr

import csv
import os
import pickle

In [2]:
recent_rows = []
with open('../tables/out.csv', mode='r') as file:
    csvFile = csv.DictReader(file)
    for lines in csvFile:
        recent_rows.append(lines)

FileNotFoundError: [Errno 2] No such file or directory: '../tables/out.csv'

In [3]:

with open("entry_table.dat", "rb") as f:
    final_table = pickle.load(f)

In [12]:
for i in final_table:
    file_name = i['Month'] + '-' + i['Day'] + '-' + i['Year'] + '.nc'
    x = xr.open_dataset('../datafiles/' + file_name)
    print(file_name)
    # print(i['Location'])
    currLocation = i['Location']

    print(currLocation.address)

    lat = []
    lon = []
    for j in range(100):
        diff_lat = (j - 1) * 0.25
        for k in range(100):
            diff_lon = (k - 1) * 0.25
            lat.append(currLocation.geometry.y.values[0] + diff_lat)
            lon.append(currLocation.geometry.x.values[0]+360 + diff_lon)


    locate =  x.sel(latitude=lat, longitude=lon, method="nearest") - 273
    # print(x)
    print(locate.coords['longitude'].to_numpy())
    print(locate.coords['latitude'].to_numpy())
    # np_d = temp.to_numpy()
    # print(np_d)
    # print(np_d[4,])
    # tempx = xr.DataArray(np_d,dims=("latitude","longitude"),)

    fp = open('../datafiles/loc_data/' + str((int)(currLocation.geometry.x.values[0] + 360)) + '-' + str((int)(currLocation.geometry.y.values[0])) + '-' + i['Month'] + '-' + i['Day'] + '-' + i['Year'] + '.nc', 'x')
    fp.close()

    locate.to_netcdf('../datafiles/loc_data/' + str((int)(currLocation.geometry.x.values[0] + 360)) + '-' + str((int)(currLocation.geometry.y.values[0])) + '-' + i['Month'] + '-' + i['Day'] + '-' + i['Year'] + '.nc')
    



01-02-2022.nc
0    Tuolumne, California, United States
Name: address, dtype: object
[239.75 240.   240.25 ... 264.   264.25 264.5 ]
[37.75 37.75 37.75 ... 62.5  62.5  62.5 ]
01-03-2022.nc
0    Georgia, United States
Name: address, dtype: object
[276.75 277.   277.25 ... 301.   301.25 301.5 ]
[32.   32.   32.   ... 56.75 56.75 56.75]
01-03-2022.nc
0    Alabama, United States
Name: address, dtype: object
[273.   273.25 273.5  ... 297.25 297.5  297.75]
[33.   33.   33.   ... 57.75 57.75 57.75]
01-03-2022.nc
0    Mississippi, United States
Name: address, dtype: object
[270.   270.25 270.5  ... 294.25 294.5  294.75]
[32.75 32.75 32.75 ... 57.5  57.5  57.5 ]


RuntimeError: NetCDF: HDF error